services:
  frontend:
    container_name: "frontend"
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env

  db:
    container_name: "db"
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data:
    name: "db_data"