services:
  frontend:
    container_name: "frontend"
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env

  server:
    container_name: "server"
    build: ./server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "
      migrate -path db/migration -database 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable' --verbose up
      && ./main
      "

  agent:
    container_name: agent
    build: ./agent
    ports:
      - 8000:8080
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      pgvector:
        condition: service_healthy

  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    ports:
      - 6024:5432
    environment:
      - POSTGRES_USER=${PGVECTOR_USER}
      - POSTGRES_PASSWORD=${PGVECTOR_PASSWORD}
      - POSTGRES_DB=${PGVECTOR_DB}
    env_file:
      - .env
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGVECTOR_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: "postgres_data"
  pgvector_data:
    name: "pgvector_data"
