basePath: /api
definitions:
  api.UserResponse:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  api.conversationData:
    properties:
      content:
        type: string
      date:
        type: string
      from:
        type: string
      id:
        type: string
      mood:
        type: string
      priority:
        type: string
      products:
        items:
          type: string
        type: array
      subject:
        type: string
      summary:
        type: string
      thread:
        $ref: '#/definitions/api.threadDetail'
      threadId:
        type: string
    type: object
  api.emailData:
    properties:
      content:
        type: string
      date:
        type: string
      from:
        type: string
      id:
        type: string
      mood:
        type: string
      priority:
        type: string
      products:
        items:
          type: string
        type: array
      subject:
        type: string
      summary:
        type: string
      thread:
        $ref: '#/definitions/api.threadDetail'
      threadId:
        type: string
    type: object
  api.emailRequest:
    properties:
      maxResults:
        type: integer
      pageToken:
        type: string
    required:
    - maxResults
    type: object
  api.emailResponse:
    properties:
      emails:
        items:
          $ref: '#/definitions/api.conversationData'
        type: array
      nextPageToken:
        type: string
    type: object
  api.googleRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  api.googleResponse:
    properties:
      accessToken:
        type: string
      message:
        type: string
      user:
        $ref: '#/definitions/api.UserResponse'
    type: object
  api.threadDetail:
    properties:
      id:
        type: string
      messages:
        items:
          $ref: '#/definitions/api.emailData'
        type: array
      snippet:
        type: string
    type: object
  api.threadRequest:
    properties:
      threadId:
        type: string
    required:
    - threadId
    type: object
  api.threadResponse:
    properties:
      messages:
        items:
          $ref: '#/definitions/api.emailData'
        type: array
    type: object
  api.updateUserRequest:
    properties:
      avatar:
        type: string
      name:
        type: string
    type: object
  api.updateUserResponse:
    properties:
      message:
        type: string
      user:
        $ref: '#/definitions/api.UserResponse'
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a documentation for Segment3d App API
  title: Segment3d App API Documentation
  version: "1.0"
paths:
  /auth/google:
    post:
      consumes:
      - application/json
      description: Authenticate user with Google OAuth token
      parameters:
      - description: Google OAuth token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.googleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Succes to login/sign up
          schema:
            $ref: '#/definitions/api.googleResponse'
      summary: Google Auth
      tags:
      - auth
  /emails:
    post:
      consumes:
      - application/json
      description: Fetch emails using Gmail API with provided OAuth token
      parameters:
      - description: OAuth token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.emailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: List of emails
          schema:
            $ref: '#/definitions/api.emailResponse'
      security:
      - BearerAuth: []
      summary: Get Emails
      tags:
      - emails
  /emails/threads:
    post:
      consumes:
      - application/json
      description: Fetch messages by thread ID using Gmail API with provided OAuth
        token
      parameters:
      - description: Thread ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.threadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: List of messages in the thread
          schema:
            $ref: '#/definitions/api.threadResponse'
      security:
      - BearerAuth: []
      summary: Get Messages by Thread ID
      tags:
      - emails
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve user information
      produces:
      - application/json
      responses:
        "200":
          description: User information retrieved successfully
          schema:
            $ref: '#/definitions/api.UserResponse'
      security:
      - BearerAuth: []
      summary: Get user data
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update user information based on the provided user ID
      parameters:
      - description: User update details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.updateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User information updated successfully
          schema:
            $ref: '#/definitions/api.updateUserResponse'
      security:
      - BearerAuth: []
      summary: Update user information
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
